routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\UserVerifiedEmail;


//Untuk API


Route::group(['middleware' => ['api_token']], function() {
    Route::middleware('throttle:30,1,default')->group(function () {
        Route::GET('public/api/v1/spacecat/acc/{room_secret_key}/{rfid}/{mac}/{ip}/{ssid}', 'ApidevicesController@proccess');
        Route::POST('public/api/v1/spacecat/dvc/{room_secret_key}', 'DevicesController@store');
        // Route::POST('api/v1/spacecat/pwd/{room_secret_key}', 'ApidevicesController@proccess_password');
        Route::POST('public/api/v1/spacecat/pwd/{room_secret_key}', 'PasswordTemp@cekpassword');
        Route::POST('public/api/v1/spacecat/paramp/{room_secret_key}', 'RoomController@cekpassword');
        // Route::POST('api/v1/spacecat/usrprm/{room_secret_key}/{rfid}', 'UsersParameters@api_store_users_parameter');
    });
});

// Untuk Web Dashboard
// Route::group(['prefix' => 'member', 'middleware' => 'auth'], function () {
Auth::routes();
Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth'], function() {

    Route::get('profile', 'UsersAdmin@index')->name('user.setting');
    Route::post('profile/change-password', 'UsersAdmin@chanagePassword')->name('change.password');

    Route::POST('resendmail/{id}', 'ProviderUser@resendemail')->name('resend.mail');
    Route::get('dashboard','ProjectsController@index')->name('dashboard');
    Route::get('project/add', 'ProjectsController@create')->name('tambah.project');
    Route::get('edit/{id_project}', 'ProjectsController@edit')->name('edit.project');
    Route::resource('projects', 'ProjectsController');

    //users
    Route::get('users/{id}', 'UsersController@index')->name('user.list');
    Route::get('search/user/{id_project}', 'UsersController@search')->name('search.user');
    Route::get('user/detail/{id_project}/{id}', 'UsersController@show')->name('lihat.user');
    Route::get('user/add/{id_project}', 'UsersController@adduser')->name('tambah.user');
    Route::put('user/update-basicinfo/{id_project}/{id_user}', 'UsersController@updatebasicinfo')->name('update.basicinfo');
    Route::put('user/update-pass/{id_project}/{id_user}', 'UsersController@updatepass')->name('update.password');
    Route::get('user/delete/{id}', 'UsersController@destroy')->name('user.destroy');
    Route::get('user/save/{id}', 'UsersController@destroy')->name('user.store');
    Route::get('user/parameters/{id_project}/{id_user}/{id_parameters}', 'UsersController@logparameters')->name('user.log.parameters');
    Route::resource('user', 'UsersController');

    //room
    Route::get('placement/{id}', 'RoomController@index')->name('daftar.placement');
    Route::get('placement/detail/{id_project}/{id}', 'RoomController@show')->name('placement.detail');
    Route::get('placement/edit/{id_project}/{id}', 'RoomController@edit')->name('placement.edit');
    Route::get('placement/add/{id}', 'RoomController@create')->name('placement.addnew');
    Route::PUT('placement/update/{id}', 'RoomController@update')->name('placement.update');
    Route::get('deleteroom/{id}', 'RoomController@destroy')->name('room.delete');

    Route::get('settings/{id_project}/{id_room}', 'RoomController@settings')->name('placement.settings');
    Route::POST('settings/update/{id_project}/{id_room}', 'RoomController@updatesettings')->name('placement.update.settings');
    Route::get('settings/edit/{id_project}/{id_room}/{id_parameter}', 'RoomController@editsettings')->name('placement.edit.settings');
    Route::PUT('settings/save/{id_project}/{id_room}/{id_parameter}', 'RoomController@savesettings')->name('placement.save.settings');
    Route::resource('room', 'RoomController');

    /// TIDAK DIPAKAI LAGI
    Route::GET('parameter/{id_porject}', 'ParametersUserController@index')->name('parameter.list');
    Route::GET('parameter/add/{id_project}', 'ParametersUserController@create')->name('parameter.add');
    Route::POST('parameter/save/{id_project}', 'ParametersUserController@store')->name('parameter.save');
    Route::GET('parameter/edit/{id_project}/{id_parameter}', 'ParametersUserController@show')->name('parameter.edits');
    Route::PUT('parameter/update/{id_project}/{id_parameter}', 'ParametersUserController@update')->name('parameter.updates');
    Route::GET('parameter/delete/{id}', 'ParametersUserController@destroy')->name('parameter.delete');
    Route::resource('parameter', 'ParametersUserController');
    //untuk melihat rules pada suatu room
    // Route::get('/rules/{id}', "RuleController@index")->name('rules.index/');
    /// TIDAK DIPAKAI LAGI


    Route::get('delete/{id}', 'FieldController@destroy')->name('field.delete');

    Route::POST('saverules/{id_project}/{id_room}', "RuleController@store")->name('save.rules');
    Route::PUT('rule/update/{id_project}/{id_room}/{id_rules}', "RuleController@update")->name('update.rules');
    Route::get('rule/add/{id_project}/{id_room}', "RuleController@create")->name('add.rules');
    Route::get('/edit/rule/{id}/{id_project}', "RuleController@edit");
    Route::get('rule/view/{id_project}/{id_room}/{id_rules}', 'RuleController@show')->name('show.rule');
    Route::get('rule/delete/{id}', 'RuleController@destroy')->name('delete.rules');
    Route::resource('rule', 'RuleController');


    Route::POST('storeruleaccess/{id_project}/{id_rooom}', "RuleController@storeruleaccess")->name('save.rule');
    Route::POST('storeschedule/{id_project}/{id_rooom}', "RuleController@storeschedule")->name('save.schedule');
    Route::POST('update/{id_room}', "RuleController@update")->name('update.rules_access');

    Route::get('devices/{id}', "DevicesController@index")->name('list.device');
    Route::resource('devices', 'DevicesController');
    Route::get('deletedevices/{id}', 'DevicesController@destroy')->name('devices.delete');


    Route::get('logs/{id_project}', "LogDataController@index")->name('log');
    Route::resource('logs', "LogDataController");
    // Route::get('get/schedule/{id}', "LogDataController@LogDataController")->name('get.log');
    Route::get('log/{id_project}/{id_room}', "LogDataController@getCompleteLog")->name('get.complete.log');


    Route::get('user/settings', "UsersAdmin@index")->name('show.useradmin');

    // ADMIN ONLY

    // Route::get('/administrator/manage/')
});

Route::POST('register/github', 'ProviderUser@create')->name('redirect.github');
Route::get('login/github', 'Auth\LoginController@redirectToProvider')->name('login.github');
Route::get('login/github/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
// Route::get('sentemail', 'JobMailController@enqueue');
Route::get('error', function(){
    return view('error_pages.404');
});
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// verifikasi user ketika sudah register.
Route::get('verify/{token}', 'Auth\RegisterController@verifyEmail')->name('verifymail');

Route::get('/', function () {
//    url('/login');
    return redirect()->guest('login');
});

resources/views/user_pages/add_user.blade.php
@extends('layouts.mainlayout')
@section('title', $page_title)
@section('content')

    <!-- begin:: Content -->
    <div class="kt-container  kt-grid__item kt-grid__item--fluid mt-3 mb-3">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="kt-subheader__main mb-3">
                    <span class="kt-subheader__separator kt-subheader__separator--v"></span>
                    <ul class="breadcrumb">
                        <li><a href="{{route('dashboard')}}">Dashboard</a></li>
                        <li><a href="{{ route('projects.show', $id_projects) }}">Projects</a></li>
                        <li><a href="{{route('user.list', $id_projects)}}">User</a></li>
                        <li>Add New</li>
                    </ul>
                </div>
                <div class="kt-portlet kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile" id="kt_page_portlet">
                    <div class="kt-portlet__head kt-portlet__head--lg">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">Add New User<small>Fill out forms below</small></h3>
                        </div>
                        <div class="kt-portlet__head-toolbar">
                            {{-- <a href="javascript:history.back()" class="btn btn-clean kt-margin-r-10">
                                <i class="la la-arrow-left"></i>
                                <span class="kt-hidden-mobile">Back</span>
                            </a> --}}
                            <div class="btn-group">
                                <button type="button" class="btn btn-brand" id="save" onclick="addSubmit()">
                                    <i class="la la-check"></i>
                                    <span class="kt-hidden-mobile">Save</span>
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class="kt-portlet__body">
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-8">
                                {{-- <div id="result"> </div> --}}

                                <div style="display:none" class="alert alert-solid-danger alert-bold"  role="alert">
                                </div>
                            </div>
                        </div>

                        <form class="kt-form" id="adduser" method="post" action="javascript:void(0)"  enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-2"></div>
                                <div class="col-8">
                                    <div class="kt-section kt-section--first">
                                        <div class="kt-section__body">
                                            <input type="hidden" name="id" id="id" value="{{ $id_projects }}">
                                            <h3 class="kt-section__title kt-section__title-sm">Basic Info:</h3>
                                            <div class="form-group row">
                                                <label class="col-3 col-lg-3 col-form-label">Avatar</label>
                                                <div class="col-9 col-lg-9">
                                                    <div class="kt-avatar kt-avatar--outline" id="kt_user_avatar">
                                                        <img class="kt-avatar__holder" id="imgcontainer" src= "{{ asset('media/users/default.jpg') }}"></img>
                                                        <label class="kt-avatar__upload" data-toggle="kt-tooltip" title="" data-original-title="Upload Avatar">
                                                            <i class="fa fa-pen"></i>
                                                            <input type="file" name="profile_avatar" id="profile_avatar">
                                                        </label>
                                                        <span class="kt-avatar__cancel" data-toggle="kt-tooltip" title="" data-original-title="Cancel avatar">
                                                            <i class="fa fa-times"></i>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-3 col-lg-3 col-form-label">Name</label>
                                                <div class="col-9 col-lg-9">
                                                    <input class="form-control" name="name" type="text" placeholder="Full Name" value="{{ old('name') }}">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-3  col-form-label">Email</label>
                                                <div class="col-9">
                                                    <input class="form-control" name="email" type="text" placeholder="Enter your Email" value="{{ old('email') }}">
                                                    <span class="form-text text-muted">We'll never share your email with anyone else.</span>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Phone Nr</label>
                                                <div class="col-9">
                                                    <input class="form-control" name="phonenr" type="text" placeholder="08123456789" value="{{ old('phonenr') }}">
                                                    <span class="form-text text-muted">We'll never share your phone number with anyone else.</span>
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-3 col-lg-3 col-form-label" for="statusrule">Status :</label>
                                                <div class="col-9 col-lg-9">
                                                    <span class="kt-switch">
                                                        <label>
                                                            <input type="checkbox" value='1' checked="checked" name="status"/>
                                                            <span></span>
                                                        </label>
                                                    </span>
                                                </div>
                                            </div>
                                            <h3 class="kt-section__title kt-section__title-sm">Security:</h3>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">RFID</label>
                                                <div class="col-9">
                                                    <input class="form-control" name="rfid" type="text"  min="0" max="99999999999999999" placeholder="Enter RFID Number">
                                                    <span class="form-text text-muted">Click <a class="kt-link" href="#">here</a> for help how to get RFID number.</span>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-3 col-lg-3 col-form-label">Password</label>
                                                <div class="col-9 col-lg-9">
                                                    <input class="form-control" name="password" type="password" placeholder="Enter Password">
                                                    <span class="form-text text-muted">The password is optional and make sure your devices have keypad!</span>
                                                </div>
                                                </br>
                                                </br>
                                                </br>

                                            </div>
                                            <div class="form-group row">
                                                <div class="col-3"></div>
                                                <div class="col-9 col-lg-9">
                                                    <input class="form-control" name="repassword" type="password" placeholder="Repeat Password">
                                                </div>
                                            </div>
                                            <h3 class="kt-section__title kt-section__title-sm">Miscellaneous:</h3>
                                            <div class="form-group form-group-last row">
                                                <label class="col-3 col-form-label">About User</label>
                                                <div class="col-9">
                                                    <textarea  name="description" class="form-control" id="description" rows="5">{{ old('description') }}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-2"></div>
                            </div>
                            <div class="kt-portlet__foot">
                                <div class="kt-form__actions">

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
    <!-- end:: Content -->
<script>


function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#imgcontainer').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

$("#profile_avatar").change(function(){
    readURL(this);
});


$(document).ready(function(e){

$('#adduser').on('submit',(function(e) {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
});

e.preventDefault();

var formData = new FormData(this);
        $.ajax({
            type:'POST',
            url: "{{ route('user.store')}}",
            data:formData,
            cache:false,
            contentType: false,
            processData: false,
            success:function(data){
                window.location = '{{ route('user.list', $id_projects) }}'
                $('#original').attr('src', 'public/media/users/'+ data.profile_avatar);
                $('#thumbImg').attr('src', 'public/media/users/thumbnail/'+ data.profile_avatar);
            },
            error: function(request, status, error){

                json  = $.parseJSON(request.responseText);
                // console.log(json);

                $('#save').removeClass('kt-spinner kt-spinner--right kt-spinner--sm kt-spinner--light').attr('disabled', false);
                // window.location = '{{ route('tambah.user', $id_projects) }}'
                $.each(json.errors, function(key, value){
                    $('.alert-solid-danger').show();
                    $('.alert-solid-danger').css('display','block');
                    $('.alert-solid-danger').append('<li class="alert-text" style:block>'+value+'</li>');
                });
                $("#result").html('');

            }
        });


    }));
});

function addSubmit(){
    $('.alert-solid-danger').hide();
    $('.alert-solid-danger').html('');

    $('#adduser').submit();
    $('#save').addClass('kt-spinner kt-spinner--right kt-spinner--sm kt-spinner--light').attr('disabled', true);
}

</script>

@endsection

resources/views/user_pages/edit_user.blade.php
@extends('layouts.mainlayout')
@section('title', 'Dashboard')
@section('content')
       
    <!-- begin:: Content Head -->
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container ">
            <div class="kt-subheader__main">
               
            </div>
            <div class="kt-subheader__toolbar">

                <a href="#" class="">

                </a>

 
            </div>
        </div>
    </div>
    <!-- end:: Content Head -->
    <!-- begin:: Content -->
    <div class="kt-container  kt-grid__item kt-grid__item--fluid">
        <!--Begin::Section-->
        
        <div class="row">
            <div class="col-lg-12">
                <div class="kt-portlet kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile" id="kt_page_portlet">
                    <div class="kt-portlet__head kt-portlet__head--lg">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">Edit User<small>Fill out forms below</small></h3>
                        </div>
                        <div class="kt-portlet__head-toolbar">
                        <a href="javascript:history.back()" class="btn btn-clean kt-margin-r-10">
                                <i class="la la-arrow-left"></i>
                                <span class="kt-hidden-mobile">Back</span>
                            </a>
                            <div class="btn-group">
                                <button type="button" class="btn btn-brand" onclick="addSubmit()">
                                    <i class="la la-check"></i> 
                                    <span class="kt-hidden-mobile">Save</span>
                                </button>
                                <button type="button" class="btn btn-brand dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                </button>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <ul class="kt-nav">
                                        <li class="kt-nav__item">
                                            <a href="#" class="kt-nav__link">
                                                <i class="kt-nav__link-icon flaticon2-edit-interface-symbol-of-pencil-tool"></i>
                                                <span class="kt-nav__link-text">Save & edit</span>
                                            </a>
                                        </li>
                                        <li class="kt-nav__item">
                                            <a href="#" class="kt-nav__link">
                                                <span class="kt-nav__link-text">Save & add new</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="kt-portlet__body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div><br />
                        @endif
                        <form class="kt-form" id="adduser" method="post" action="{{ route('user.update', $id) }}">
                                @method('PUT')
                            @csrf
                           
                            <div class="row">
                                <div class="col-xl-2"></div>
                                <div class="col-xl-8">
                                    <div class="kt-section kt-section--first">
                                        <div class="kt-section__body">
                                            <input type="hidden" name="id" id="id" value="{{ $id }}">
                                            <input type="hidden" name="id_project" id="id_project" value="{{ $users->id_project}}">
                                            <h3 class="kt-section__title kt-section__title-sm">Basic Info:</h3>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Name</label>
                                                <div class="col-9">
                                                    <input class="form-control" name="name" type="text" placeholder="Full Name" value="{{ old('nama', $users->name) }}">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Email</label>
                                                <div class="col-9">
                                                    <input class="form-control" name="email" type="text" placeholder="Enter your Email" value="{{ old('email', $users->email) }}">
                                                    <span class="form-text text-muted">We'll never share your email with anyone else.</span>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Phone Nr</label>
                                                <div class="col-9">
                                                    <input class="form-control" name="phonenr" type="text" placeholder="08123456789" value="{{ old('phonenr', $users->phonenr) }}">
                                                    <span class="form-text text-muted">We'll never share your phone number with anyone else.</span>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Status</label>
                                                <div class="col-4" >
                                                    <select class="form-control" id="status" name="status">
                                                        <option value="1">Active</option>
                                                        <option value="0">InActive</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <h3 class="kt-section__title kt-section__title-sm">Security:</h3>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">RFID</label>
                                                <div class="col-9">
                                                    <input class="form-control" name="rfid" type="text"  min="0" max="99999999999999999" placeholder="Enter RFID Number">
                                                    <span class="form-text text-muted">Click <a class="kt-link" href="#">here</a> for help how to get RFID number.</span>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Password</label>
                                                <div class="col-4">
                                                    <input class="form-control" name="password" type="password" placeholder="Enter Password">
                                                </div>
                                                <div class="col-5">
                                                    <input class="form-control" name="repassword" type="password" placeholder="Repeat Password">
                                                </div>
                                            </div>
                                            <h3 class="kt-section__title kt-section__title-sm">Miscellaneous:</h3>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Image</label>
                                                <div></div>
                                                <div class="col-9 ">
                                                    <div class="col-12">
                                                        <label class="custom-file-label" for="customFile">Choose Image</label>
                                                        <input type="file" class="custom-file-input" id="image" name="image">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group form-group-last row">
                                                <label class="col-3 col-form-label">Description</label>
                                                <div class="col-9">
                                                <textarea  name="description" class="form-control" id="description" rows="5">{{old('description', $users->description)}}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-2"></div>
                            </div>
                            <div class="kt-portlet__foot">
                                <div class="kt-form__actions">
                                   
                                </div>
                            </div>
                        </form>
                    </div>
                </div>	
            <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
    <!-- end:: Content -->


<script>

    function addSubmit(){
        $('#adduser').submit();
    }

</script>

@endsection