routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\UserVerifiedEmail;


//Untuk API


Route::group(['middleware' => ['api_token']], function() {
    Route::middleware('throttle:30,1,default')->group(function () {
        Route::GET('public/api/v1/spacecat/acc/{room_secret_key}/{rfid}/{mac}/{ip}/{ssid}', 'ApidevicesController@proccess');
        Route::POST('public/api/v1/spacecat/dvc/{room_secret_key}', 'DevicesController@store');
        // Route::POST('api/v1/spacecat/pwd/{room_secret_key}', 'ApidevicesController@proccess_password');
        Route::POST('public/api/v1/spacecat/pwd/{room_secret_key}', 'PasswordTemp@cekpassword');
        Route::POST('public/api/v1/spacecat/paramp/{room_secret_key}', 'RoomController@cekpassword');
        // Route::POST('api/v1/spacecat/usrprm/{room_secret_key}/{rfid}', 'UsersParameters@api_store_users_parameter');
    });
});

// Untuk Web Dashboard
// Route::group(['prefix' => 'member', 'middleware' => 'auth'], function () {
Auth::routes();
Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth'], function() {

    Route::get('profile', 'UsersAdmin@index')->name('user.setting');
    Route::post('profile/change-password', 'UsersAdmin@chanagePassword')->name('change.password');

    Route::POST('resendmail/{id}', 'ProviderUser@resendemail')->name('resend.mail');
    Route::get('dashboard','ProjectsController@index')->name('dashboard');
    Route::get('project/add', 'ProjectsController@create')->name('tambah.project');
    Route::get('edit/{id_project}', 'ProjectsController@edit')->name('edit.project');
    Route::resource('projects', 'ProjectsController');

    //users
    Route::get('users/{id}', 'UsersController@index')->name('user.list');
    Route::get('search/user/{id_project}', 'UsersController@search')->name('search.user');
    Route::get('user/detail/{id_project}/{id}', 'UsersController@show')->name('lihat.user');
    Route::get('user/add/{id_project}', 'UsersController@adduser')->name('tambah.user');
    Route::put('user/update-basicinfo/{id_project}/{id_user}', 'UsersController@updatebasicinfo')->name('update.basicinfo');
    Route::put('user/update-pass/{id_project}/{id_user}', 'UsersController@updatepass')->name('update.password');
    Route::get('user/delete/{id}', 'UsersController@destroy')->name('user.destroy');
    Route::get('user/save/{id}', 'UsersController@destroy')->name('user.store');
    Route::get('user/parameters/{id_project}/{id_user}/{id_parameters}', 'UsersController@logparameters')->name('user.log.parameters');
    Route::resource('user', 'UsersController');

    //room
    Route::get('placement/{id}', 'RoomController@index')->name('daftar.placement');
    Route::get('placement/detail/{id_project}/{id}', 'RoomController@show')->name('placement.detail');
    Route::get('placement/edit/{id_project}/{id}', 'RoomController@edit')->name('placement.edit');
    Route::get('placement/add/{id}', 'RoomController@create')->name('placement.addnew');
    Route::PUT('placement/update/{id}', 'RoomController@update')->name('placement.update');
    Route::get('deleteroom/{id}', 'RoomController@destroy')->name('room.delete');

    Route::get('settings/{id_project}/{id_room}', 'RoomController@settings')->name('placement.settings');
    Route::POST('settings/update/{id_project}/{id_room}', 'RoomController@updatesettings')->name('placement.update.settings');
    Route::get('settings/edit/{id_project}/{id_room}/{id_parameter}', 'RoomController@editsettings')->name('placement.edit.settings');
    Route::PUT('settings/save/{id_project}/{id_room}/{id_parameter}', 'RoomController@savesettings')->name('placement.save.settings');
    Route::resource('room', 'RoomController');

    /// TIDAK DIPAKAI LAGI
    Route::GET('parameter/{id_porject}', 'ParametersUserController@index')->name('parameter.list');
    Route::GET('parameter/add/{id_project}', 'ParametersUserController@create')->name('parameter.add');
    Route::POST('parameter/save/{id_project}', 'ParametersUserController@store')->name('parameter.save');
    Route::GET('parameter/edit/{id_project}/{id_parameter}', 'ParametersUserController@show')->name('parameter.edits');
    Route::PUT('parameter/update/{id_project}/{id_parameter}', 'ParametersUserController@update')->name('parameter.updates');
    Route::GET('parameter/delete/{id}', 'ParametersUserController@destroy')->name('parameter.delete');
    Route::resource('parameter', 'ParametersUserController');
    //untuk melihat rules pada suatu room
    // Route::get('/rules/{id}', "RuleController@index")->name('rules.index/');
    /// TIDAK DIPAKAI LAGI


    Route::get('delete/{id}', 'FieldController@destroy')->name('field.delete');

    Route::POST('saverules/{id_project}/{id_room}', "RuleController@store")->name('save.rules');
    Route::PUT('rule/update/{id_project}/{id_room}/{id_rules}', "RuleController@update")->name('update.rules');
    Route::get('rule/add/{id_project}/{id_room}', "RuleController@create")->name('add.rules');
    Route::get('/edit/rule/{id}/{id_project}', "RuleController@edit");
    Route::get('rule/view/{id_project}/{id_room}/{id_rules}', 'RuleController@show')->name('show.rule');
    Route::get('rule/delete/{id}', 'RuleController@destroy')->name('delete.rules');
    Route::resource('rule', 'RuleController');


    Route::POST('storeruleaccess/{id_project}/{id_rooom}', "RuleController@storeruleaccess")->name('save.rule');
    Route::POST('storeschedule/{id_project}/{id_rooom}', "RuleController@storeschedule")->name('save.schedule');
    Route::POST('update/{id_room}', "RuleController@update")->name('update.rules_access');

    Route::get('devices/{id}', "DevicesController@index")->name('list.device');
    Route::resource('devices', 'DevicesController');
    Route::get('deletedevices/{id}', 'DevicesController@destroy')->name('devices.delete');


    Route::get('logs/{id_project}', "LogDataController@index")->name('log');
    Route::resource('logs', "LogDataController");
    // Route::get('get/schedule/{id}', "LogDataController@LogDataController")->name('get.log');
    Route::get('log/{id_project}/{id_room}', "LogDataController@getCompleteLog")->name('get.complete.log');


    Route::get('user/settings', "UsersAdmin@index")->name('show.useradmin');

    // ADMIN ONLY

    // Route::get('/administrator/manage/')
});

Route::POST('register/github', 'ProviderUser@create')->name('redirect.github');
Route::get('login/github', 'Auth\LoginController@redirectToProvider')->name('login.github');
Route::get('login/github/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
// Route::get('sentemail', 'JobMailController@enqueue');
Route::get('error', function(){
    return view('error_pages.404');
});
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// verifikasi user ketika sudah register.
Route::get('verify/{token}', 'Auth\RegisterController@verifyEmail')->name('verifymail');

Route::get('/', function () {
//    url('/login');
    return redirect()->guest('login');
});

resources/views/layouts/partials/footer-scripts.blade.php
<!--begin:: Global Mandatory Vendors -->
<script src="{{ asset('vendors/general/popper.js/dist/umd/popper.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/bootstrap/dist/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/js-cookie/src/js.cookie.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/moment/min/moment.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/tooltip.js/dist/umd/tooltip.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/perfect-scrollbar/dist/perfect-scrollbar.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/sticky-js/dist/sticky.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/wnumb/wNumb.js') }}" type="text/javascript"></script>
<!--end:: Global Mandatory Vendors -->

<!--begin:: Global Optional Vendors -->

<script src="{{ asset('vendors/general/jquery-form/dist/jquery.form.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/custom/js/vendors/bootstrap-datepicker.init.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/bootstrap-timepicker/js/bootstrap-timepicker.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/custom/js/vendors/bootstrap-timepicker.init.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/bootstrap-datepicker/js/bootstrap-datepicker.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/bootstrap-daterangepicker/daterangepicker.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/bootstrap-select/dist/js/bootstrap-select.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/bootstrap-switch/dist/js/bootstrap-switch.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/custom/js/vendors/bootstrap-switch.init.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/select2/dist/js/select2.full.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/toastr/build/toastr.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/dual-listbox/dist/dual-listbox.js')}}" type="text/javascript"></script>
<script src="{{ asset('vendors/general/bootstrap-notify/bootstrap-notify.js')}}" type="text/javascript"></script>
<!--end:: GlobalOptional Vendors -->

<!--begin::Global Theme Bundle(used by all pages) -->
<script src="{{ asset('js/scripts.bundle.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/multi.min.js') }}" type="text/javascript"></script>
<!--end::Global Theme Bundle -->

{{-- <script src="//maps.google.com/maps/api/js?key=AIzaSyBTGnKT7dt597vo9QgeQ7BFhvSRP4eiMSM" type="text/javascript"></script> --}}
{{-- <script src="{{ asset('vendors/custom/gmaps/gmaps.js') }}" type="text/javascript"></script> --}}
<!--end::Page Vendors -->

<!--begin::Page Scripts(used by this page) -->
@stack('notify')
{{-- <script src="{{ asset('js/pages/dashboard.js') }}" type="text/javascript"></script> --}}
<!--end::Page Scripts -->

   {{-- <!--begin::Page Scripts(used by this page) -->
   <script src="{{ asset('js/pages/components/extended/dual-listbox.js') }}" type="text/javascript"></script>
   <!--end::Page Scripts --> --}}
  <!-- begin::Global Config(global config for global JS sciprts) -->
  <script type="text/javascript">

    @if(Session::has('success'))
        $.notify({
            title: 'Success',
            message: '  {!! session()->get('success') !!}',
        });
    @endif

    var KTAppOptions = {"colors":{"state":{"brand":"#374afb","light":"#ffffff","dark":"#282a3c","primary":"#5867dd","success":"#34bfa3","info":"#36a3f7","warning":"#ffb822","danger":"#fd3995"},"base":{"label":["#c5cbe3","#a1a8c3","#3d4465","#3e4466"],"shape":["#f0f3ff","#d9dffa","#afb4d4","#646c9a"]}}};

    // function deleteModal(id){
    //     var id = id;
    //     var url = '{{ route("projects.destroy", ":id")}}';
    //     url = url.replace(':id', id);
    //     $("#formDeleteuser").attr('action', url);
    // }

    // function formSubmit(){
    //     $("#formDeleteuser").submit();
    // }
    //     // Private functions



    $('#list_room').multi({
        'search_placeholder': 'Search Users ...',
        'non_selected_header': 'Users',
        'selected_header': 'Selected'
    });

    function deleteModal(id){
        var id = id;
        var url = '{{ route("projects.destroy", ":id")}}';
        url = url.replace(':id', id);
        $("#formDeleteProject").attr('action', url);
    }

    function formProjectSubmit(){
        $("#formDeleteProject").submit();
    }
/////////////////////
    function deleteModalUser(id){
        var id = id;
        var url = '{{ route("user.destroy", ":id")}}';
        url = url.replace(':id', id);
        $("#formDeleteUser").attr('action', url);
    }

    function formDeletetSubmit(){
        $("#formDeleteUser").submit();
    }
    ///////////////////////
    function deleteModalRoom(id){
        var id = id;
        var url = '{{ route("room.destroy", ":id")}}';
        url = url.replace(':id', id);
        $("#formDeleteUser").attr('action', url);
    }

    function formDeletetSubmit(){
        $("#formDeleteUser").submit();
    }
    //////////////////


    ////////////////
    //delete schedule
    function deletrule(id){
        var id = id;
        var url = '{{ route("delete.rules", ":id")}}';
        url = url.replace(':id', id);
        $("#formDeleteRule").attr('action', url);
    }

    function formDeleteRuleSubmit(){
        console.log("deleting");
        $("#formDeleteRule").submit();
    }


    //delete user parameter
    function deleteUserParameter(id){
        console.log(id);
        var id = id;
        var url = '{{ route("parameter.destroy", ":id")}}';
        url = url.replace(':id', id);
        console.log(url);
        $("#formDeleteParam").attr('action', url);
    }

    function formDeleteParamSubmit(){
        console.log("deleting");
        $("#formDeleteParam").submit();
    }

///////////////
    $('#time_end , #time_start').timepicker({
        minuteStep: 1,
        defaultTime: '0',
        showSeconds: false,
        showMeridian: false,
        snapToStep: true
    });


    $("#kt_datepicker_2, #kt_datepicker_2_validate").datepicker( {
         todayHighlight: !0, orientation: "bottom left",
         format: 'dd/M/yyyy'
        }
    ),
    $("#kt_datepicker_2_modal").datepicker( {
         todayHighlight: !0, orientation: "bottom left",
         format: 'dd/M/yyyy'
    });

    $("#kt_datetimepicker_6").datetimepicker( {
        format: "yyyy/mm/dd", todayHighlight: !0, autoclose: !0, startView: 2, minView: 2, forceParse: 0, pickerPosition: "bottom-left"
    });

        // Dual Listbox
    var listBoxes = $('.kt-dual-listbox');

    listBoxes.each(function(){
        var $this = $(this);
        var id = '#' + $this.attr('id');
        // get titles
        var availableTitle = ($this.attr('data-available-title') != null) ? $this.attr('data-available-title') : 'Available options';
        var selectedTitle = ($this.attr('data-selected-title') != null) ? $this.attr('data-selected-title') : 'Selected options';

        // get button labels
        var addLabel = ($this.attr('data-add') != null) ? $this.attr('data-add') : 'Add';
        var removeLabel = ($this.attr('data-remove') != null) ? $this.attr('data-remove') : 'Remove';
        var addAllLabel = ($this.attr('data-add-all') != null) ? $this.attr('data-add-all') : 'Add All';
        var removeAllLabel = ($this.attr('data-remove-all') != null) ? $this.attr('data-remove-all') : 'Remove All';

        // get options
        var options = [];
        $this.children('option').each(function(){
            var value = $(this).val();
            var label = $(this).text();
            var selected = ($(this).is(':selected')) ? true : false;
            options.push({ text: label, value: value, selected: selected });
        });

      // get search option
      var search = ($this.attr('data-search') != null) ? $this.attr('data-search') : "";

      // clear duplicates
      $this.empty();
            // init dual listbox
      let dualListBox = new DualListbox('#kt-dual-listbox',{
          addEvent: function(value) {
            //   console.log(value);
          },
          removeEvent: function(value) {
            //   console.log(value);
          },
          availableTitle: availableTitle,
          selectedTitle: selectedTitle,
          addButtonText: addLabel,
          removeButtonText: removeLabel,
          addAllButtonText: addAllLabel,
          removeAllButtonText: removeAllLabel,
          options: options
      });

      if (search == "false"){
        dualListBox.search.classList.add('dual-listbox__search--hidden');
      }
    });


</script>
      <!-- end::Global Config -->

resources/views/layouts/partials/footer.blade.php
	<!-- begin:: Footer -->

<div class="kt-footer  kt-footer--extended  kt-grid__item" id="kt_footer">
		<div class="kt-footer__top">
		<div class="kt-container ">
			<div class="row">
				<div class="col-lg-4">
					<div  class="kt-footer__section">
						<h3 class="kt-footer__title">About</h3>
						<div class="kt-footer__content">
											I'm Arif, i deciding to making this web app and arduino libraries to public with a bit hope that all this can be useful for many people.
											<br>
											So, any help or contribution will be appreciated. <a href="https://github.com/AsyaSyarif/RFID-Spacecat/issues" target="_blank">This way</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div  class="kt-footer__section">
						<h3 class="kt-footer__title">Quick Links</h3>
						<div class="kt-footer__content">
							<div class="kt-footer__nav">
								<div class="kt-footer__nav-section">
									<a href="#">Documentation</a>
									<a href="https://github.com/AsyaSyarif/RFID-Spacecat">Library</a>
									<a href="#">API</a>
								</div>
								<div class="kt-footer__nav-section">
									<a href="https://github.com/AsyaSyarif/RFID-Spacecat/issues">Report Bug</a>
									<a href="#">Buy Me A Coffee</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div  class="kt-footer__section">
						<h3 class="kt-footer__title">Get In Touch</h3>
						<div class="kt-footer__content">
							<form action="" class="kt-footer__subscribe">
								<div class="input-group">
									<input type="text" class="form-control" placeholder="Enter Your Email">
									<div class="input-group-append">
										<button class="btn btn-brand" type="button">Join</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="kt-footer__bottom">
	<div class="kt-container ">
		<div class="kt-footer__wrapper">
			<div class="kt-footer__logo">
				<a href="demo2/index.html">
					<img alt="Logo" src="{{ asset('media/logos/logo-2.png') }}">
				</a>
				<div class="kt-footer__copyright">
                    <?php
                    $fromYear = 2018;
                    $thisYear = (int)date('Y');
                    echo $fromYear . (($fromYear != $thisYear) ? '-' . $thisYear : '');?>
					&nbsp;&copy;&nbsp;
					<span>Developed and Maintained with&nbsp;</span class="hred">❤<span>&nbsp;by </span>
					<a href="https://www.asyarif.net" target="_blank">Arif</a>
				</div>
			</div>
			<div class="kt-footer__menu">
				<a href="http://t.me/asya_syarif" target="_blank">Telegram</a>
				<a href="https://github.com/AsyaSyarif/RFID-Spacecat" target="_blank">GitHub</a>
				<a href="#" class="text-muted" target="_blank">App Version beta</a>
			</div>
		</div>
	</div>
</div>

</div><!-- end:: Page -->
</div>
</div>

resources/views/layouts/partials/head.blade.php
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700">

<link href="{{ asset('vendors/general/perfect-scrollbar/css/perfect-scrollbar.css') }}" rel="stylesheet" type="text/css" />

<link href="{{ asset('vendors/general/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/general/bootstrap-datetime-picker/css/bootstrap-datetimepicker.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/general/bootstrap-timepicker/css/bootstrap-timepicker.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/general/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/general/bootstrap-select/dist/css/bootstrap-select.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/general/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/general/select2/dist/css/select2.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/general/toastr/build/toastr.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/general/dual-listbox/dist/dual-listbox.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/custom/vendors/line-awesome/css/line-awesome.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/custom/vendors/flaticon/flaticon.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/custom/vendors/flaticon2/flaticon.css')}}" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/multi.min.css')}}" rel="stylesheet" type="text/css"/>


<link href="{{ asset('css/style.bundle.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('css/custom/style.css') }}" rel="stylesheet" type="text/css" />

<script src="{{ asset('vendors/general/jquery/dist/jquery.js')}}" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js" type="text/javascript"></script>
<link rel="shortcut icon" href="{{ asset('media/logos/favicon.ico') }}" />