routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\UserVerifiedEmail;


//Untuk API


Route::group(['middleware' => ['api_token']], function() {
    Route::middleware('throttle:30,1,default')->group(function () {
        Route::GET('public/api/v1/spacecat/acc/{room_secret_key}/{rfid}/{mac}/{ip}/{ssid}', 'ApidevicesController@proccess');
        Route::POST('public/api/v1/spacecat/dvc/{room_secret_key}', 'DevicesController@store');
        // Route::POST('api/v1/spacecat/pwd/{room_secret_key}', 'ApidevicesController@proccess_password');
        Route::POST('public/api/v1/spacecat/pwd/{room_secret_key}', 'PasswordTemp@cekpassword');
        Route::POST('public/api/v1/spacecat/paramp/{room_secret_key}', 'RoomController@cekpassword');
        // Route::POST('api/v1/spacecat/usrprm/{room_secret_key}/{rfid}', 'UsersParameters@api_store_users_parameter');
    });
});

// Untuk Web Dashboard
// Route::group(['prefix' => 'member', 'middleware' => 'auth'], function () {
Auth::routes();
Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth'], function() {

    Route::get('profile', 'UsersAdmin@index')->name('user.setting');
    Route::post('profile/change-password', 'UsersAdmin@chanagePassword')->name('change.password');

    Route::POST('resendmail/{id}', 'ProviderUser@resendemail')->name('resend.mail');
    Route::get('dashboard','ProjectsController@index')->name('dashboard');
    Route::get('project/add', 'ProjectsController@create')->name('tambah.project');
    Route::get('edit/{id_project}', 'ProjectsController@edit')->name('edit.project');
    Route::resource('projects', 'ProjectsController');

    //users
    Route::get('users/{id}', 'UsersController@index')->name('user.list');
    Route::get('search/user/{id_project}', 'UsersController@search')->name('search.user');
    Route::get('user/detail/{id_project}/{id}', 'UsersController@show')->name('lihat.user');
    Route::get('user/add/{id_project}', 'UsersController@adduser')->name('tambah.user');
    Route::put('user/update-basicinfo/{id_project}/{id_user}', 'UsersController@updatebasicinfo')->name('update.basicinfo');
    Route::put('user/update-pass/{id_project}/{id_user}', 'UsersController@updatepass')->name('update.password');
    Route::get('user/delete/{id}', 'UsersController@destroy')->name('user.destroy');
    Route::get('user/save/{id}', 'UsersController@destroy')->name('user.store');
    Route::get('user/parameters/{id_project}/{id_user}/{id_parameters}', 'UsersController@logparameters')->name('user.log.parameters');
    Route::resource('user', 'UsersController');

    //room
    Route::get('placement/{id}', 'RoomController@index')->name('daftar.placement');
    Route::get('placement/detail/{id_project}/{id}', 'RoomController@show')->name('placement.detail');
    Route::get('placement/edit/{id_project}/{id}', 'RoomController@edit')->name('placement.edit');
    Route::get('placement/add/{id}', 'RoomController@create')->name('placement.addnew');
    Route::PUT('placement/update/{id}', 'RoomController@update')->name('placement.update');
    Route::get('deleteroom/{id}', 'RoomController@destroy')->name('room.delete');

    Route::get('settings/{id_project}/{id_room}', 'RoomController@settings')->name('placement.settings');
    Route::POST('settings/update/{id_project}/{id_room}', 'RoomController@updatesettings')->name('placement.update.settings');
    Route::get('settings/edit/{id_project}/{id_room}/{id_parameter}', 'RoomController@editsettings')->name('placement.edit.settings');
    Route::PUT('settings/save/{id_project}/{id_room}/{id_parameter}', 'RoomController@savesettings')->name('placement.save.settings');
    Route::resource('room', 'RoomController');

    /// TIDAK DIPAKAI LAGI
    Route::GET('parameter/{id_porject}', 'ParametersUserController@index')->name('parameter.list');
    Route::GET('parameter/add/{id_project}', 'ParametersUserController@create')->name('parameter.add');
    Route::POST('parameter/save/{id_project}', 'ParametersUserController@store')->name('parameter.save');
    Route::GET('parameter/edit/{id_project}/{id_parameter}', 'ParametersUserController@show')->name('parameter.edits');
    Route::PUT('parameter/update/{id_project}/{id_parameter}', 'ParametersUserController@update')->name('parameter.updates');
    Route::GET('parameter/delete/{id}', 'ParametersUserController@destroy')->name('parameter.delete');
    Route::resource('parameter', 'ParametersUserController');
    //untuk melihat rules pada suatu room
    // Route::get('/rules/{id}', "RuleController@index")->name('rules.index/');
    /// TIDAK DIPAKAI LAGI


    Route::get('delete/{id}', 'FieldController@destroy')->name('field.delete');

    Route::POST('saverules/{id_project}/{id_room}', "RuleController@store")->name('save.rules');
    Route::PUT('rule/update/{id_project}/{id_room}/{id_rules}', "RuleController@update")->name('update.rules');
    Route::get('rule/add/{id_project}/{id_room}', "RuleController@create")->name('add.rules');
    Route::get('/edit/rule/{id}/{id_project}', "RuleController@edit");
    Route::get('rule/view/{id_project}/{id_room}/{id_rules}', 'RuleController@show')->name('show.rule');
    Route::get('rule/delete/{id}', 'RuleController@destroy')->name('delete.rules');
    Route::resource('rule', 'RuleController');


    Route::POST('storeruleaccess/{id_project}/{id_rooom}', "RuleController@storeruleaccess")->name('save.rule');
    Route::POST('storeschedule/{id_project}/{id_rooom}', "RuleController@storeschedule")->name('save.schedule');
    Route::POST('update/{id_room}', "RuleController@update")->name('update.rules_access');

    Route::get('devices/{id}', "DevicesController@index")->name('list.device');
    Route::resource('devices', 'DevicesController');
    Route::get('deletedevices/{id}', 'DevicesController@destroy')->name('devices.delete');


    Route::get('logs/{id_project}', "LogDataController@index")->name('log');
    Route::resource('logs', "LogDataController");
    // Route::get('get/schedule/{id}', "LogDataController@LogDataController")->name('get.log');
    Route::get('log/{id_project}/{id_room}', "LogDataController@getCompleteLog")->name('get.complete.log');


    Route::get('user/settings', "UsersAdmin@index")->name('show.useradmin');

    // ADMIN ONLY

    // Route::get('/administrator/manage/')
});

Route::POST('register/github', 'ProviderUser@create')->name('redirect.github');
Route::get('login/github', 'Auth\LoginController@redirectToProvider')->name('login.github');
Route::get('login/github/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
// Route::get('sentemail', 'JobMailController@enqueue');
Route::get('error', function(){
    return view('error_pages.404');
});
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// verifikasi user ketika sudah register.
Route::get('verify/{token}', 'Auth\RegisterController@verifyEmail')->name('verifymail');

Route::get('/', function () {
//    url('/login');
    return redirect()->guest('login');
});

resources/views/rules_pages/add_shcedule.blade.php
@extends('layouts.mainlayout')
@section('title', 'Dashboard')
@section('content')

    <!-- begin:: Content Head -->
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container ">
            <div class="kt-subheader__main">

                
            </div>
            <div class="kt-subheader__toolbar">

            </div>
        </div>
    </div>
    <!-- end:: Content Head -->
    <!-- begin:: Content -->
    <div class="kt-container  kt-grid__item kt-grid__item--fluid">
            <div class="row">
            <!-- Isi Content disini -->
                <div class="col-lg-12">
                    <div class="kt-portlet kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile" id="kt_page_portlet">
                        <div class="kt-portlet__head kt-portlet__head--lg">
                            <div class="kt-portlet__head-label">
                                <h3 class="kt-portlet__head-title">Add Schedule<small>Fill out forms below</small></h3>
                            </div>
                            <div class="kt-portlet__head-toolbar">
                            <a href="{{ url()->previous() }}" class="btn btn-clean btn-bold kt-margin-r-10">
                                    <i class="la la-arrow-left"></i>
                                    <span class="kt-hidden-mobile">Back</span>
                                </a>
                                <div class="btn-group">
                                    <button type="button" id="btnSaveRule" class="btn btn-brand btn-bold" onclick="addSubmit()">
                                        <i class="la la-check"></i> 
                                        <span class="kt-hidden-mobile">Save</span>
                                    </button>
                                    <button type="button" class="btn btn-brand dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <ul class="kt-nav">
                                            <li class="kt-nav__item">
                                                <a href="#" class="kt-nav__link">
                                                    <i class="kt-nav__link-icon flaticon2-edit-interface-symbol-of-pencil-tool"></i>
                                                    <span class="kt-nav__link-text">Save & edit</span>
                                                </a>
                                            </li>
                                            <li class="kt-nav__item">
                                                <a href="#" class="kt-nav__link">
                                                    <span class="kt-nav__link-text">Save & add new</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="kt-portlet__body">
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                            @endif
                            <form class="kt-form" id="addrule" method="post" action="{{ route('rule.store') }}">
                                @method('POST')
                                {{ csrf_field() }}
                            
                                <div class="row">
                                    <div class="col-xl-2"></div>
                                    <div class="col-xl-9">
                                        <!--begin::Portlet-->
                            
                                        <!--end::Portlet-->
                                    </div>
                                    <div class="col-xl-2"></div>
                                </div>
                            </form>
                        </div>
                    </div>	
            <!--end::Portlet-->
            </div>
        </div>
    <!--End::Section-->
    </div>
    <!-- end:: Content -->

        <!--begin::Modal-->
        <div class="modal fade" id="scheduleModal" name="scheduleModal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="">Schedule</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" class="la la-remove"></span>
                        </button>
                    </div>
                    <form class="kt-form kt-form--fit kt-form--label-right">
                        <div class="modal-body">
                            <div class="form-group row">
                                <label for="example-number-input" class="col-3 col-form-label">Name</label>
                                <div class="col-8">
                                    <input class="form-control" type="text" value="" placeholder="Enter Schedule Name" name="name_schedule" id="name_schedule">
                                </div>
                            </div>
                            <div class="form-group row">
                                    <label class="col-lg-3 col-form-label">Day</label>
                                    <div class="col-lg-8">
                                        <select class="form-control" id="dayschedule" name="dayschedule">
                                            <option value="none" selected disabled hidden>  Select Day </option> 
                                            <option value="Monday">Monday</option>
                                            <option value="Tuesday">Tuesday</option>
                                            <option value="Wednesday">Wednesday</option>
                                            <option value="Thrusday">Thrusday</option>
                                            <option value="Friday">Friday</option>
                                            <option value="Saturday">Saturday</option>
                                            <option value="Sunday">Sunday</option>
                                        </select>
                                    </div>
                            </div>
                            <div class="kt-divider mb-4"><span></span>
                            </div>
                            <div class="form-group row">
                                <label class="col-form-label col-lg-3 col-sm-12">Time Start</label>
                                <div class="col-lg-8 col-md-9 col-sm-12">
                                    <div class="input-group timepicker">
                                        <input class="form-control" id="time_start" name="time_start" readonly placeholder="Select time" type="text"/>
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="la la-clock-o"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <span class="form-text text-muted">format :  hh/mm</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-form-label col-lg-3 col-sm-12">Time End</label>
                                <div class="col-lg-8 col-md-9 col-sm-12">
                                    <div class="input-group timepicker">
                                        <input class="form-control" id="time_end" name="time_end" readonly placeholder="Select time" type="text"/>
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="la la-clock-o"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <span class="form-text text-muted">format :  hh/mm</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="example-number-input" class="col-3 col-form-label">Offset Time</label>
                                <div class="col-8">
                                    <input class="form-control" type="number" name="offset_time" id="offset_time" value="0" placeholder="e.g. 15" id="example-number-input">
                                    <span class="form-text text-muted">format :  minutes</span>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <button type="button" id="applySchedule" class="btn btn-brand">Apply</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!--end::Modal-->
@endsection

resources/views/rules_pages/rules_list.blade.php
@extends('layouts.mainlayout')

@section('content')

  <!-- begin:: Content Head -->
  <div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">

            <h3 class="kt-subheader__title">
                {{ $subheader_title }}
            </h3>

            <span class="kt-subheader__separator kt-subheader__separator--v"></span>
        </div>
        <div class="kt-subheader__toolbar">

        </div>
    </div>
    </div>

    <!-- end:: Content Head -->
    <!-- begin:: Content -->
    <div class="kt-container  kt-grid__item kt-grid__item--fluid">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                    <!--begin::Portlet-->
                <div class="kt-portlet">
                    <div class="kt-portlet__body">
                        <div class="kt-widget kt-widget--user-profile-3">
                            <div class="kt-portlet__body kt-portlet__body--fit">
                                <div class="kt-widget kt-widget--user-profile-3">
                                    <div class="kt-widget__top">
                                        <div class="kt-widget__media kt-hidden-">
                                            <img src="/metronic/themes/metronic/theme/default/demo2/dist/assets/media/users/100_2.jpg" alt="image">
                                        </div>
                                        <div class="kt-widget__pic kt-widget__pic--danger kt-font-danger kt-font-boldest kt-font-light kt-hidden">
                                            ChS
                                        </div>
                                        <div class="kt-widget__content">
                                            <div class="kt-widget__head">
                                                <a href="#" class="kt-widget__username">
                                                    Charlie Stone
                                                    <i class="flaticon2-correct kt-font-success"></i>
                                                </a>

                                                <div class="kt-widget__action">
                                                    <button type="button" class="btn btn-label-success btn-sm btn-upper">ask</button>&nbsp;
                                                    <button type="button" class="btn btn-brand btn-sm btn-upper">hire</button>
                                                </div>
                                            </div>

                                            <div class="kt-widget__subhead">
                                                <a href="#"><i class="flaticon2-new-email"></i>charlie@stone.com</a>
                                                <a href="#"><i class="flaticon2-calendar-3"></i>Web Developer</a>
                                                <a href="#"><i class="flaticon2-placeholder"></i>London</a>
                                            </div>

                                            <div class="kt-widget__info">
                                                <div class="kt-widget__desc">
                                                    I distinguish three main text objektive could be merely to inform people.<br>
                                                    A second could be persuade people.You want people to bay objective
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="kt-widget__bottom">
                                        <div class="kt-widget__item">
                                            <div class="kt-widget__icon">
                                                <i class="flaticon-piggy-bank"></i>
                                            </div>
                                            <div class="kt-widget__details">
                                                <span class="kt-widget__title">Earnings</span>
                                                <span class="kt-widget__value"><span>$</span>542,500</span>
                                            </div>
                                        </div>

                                        <div class="kt-widget__item">
                                            <div class="kt-widget__icon">
                                                <i class="flaticon-confetti"></i>
                                            </div>
                                            <div class="kt-widget__details">
                                                <span class="kt-widget__title">Expenses</span>
                                                <span class="kt-widget__value"><span>$</span>675,500</span>
                                            </div>
                                        </div>

                                        <div class="kt-widget__item">
                                            <div class="kt-widget__icon">
                                                <i class="flaticon-pie-chart"></i>
                                            </div>
                                            <div class="kt-widget__details">
                                                <span class="kt-widget__title">Net</span>
                                                <span class="kt-widget__value"><span>$</span>412,400</span>
                                            </div>
                                        </div>

                                        <div class="kt-widget__item">
                                            <div class="kt-widget__icon">
                                                <i class="flaticon-file-2"></i>
                                            </div>
                                            <div class="kt-widget__details">
                                                <span class="kt-widget__title">35 Tasks</span>
                                                <a href="#" class="kt-widget__value kt-font-brand">View</a>
                                            </div>
                                        </div>

                                        <div class="kt-widget__item">
                                            <div class="kt-widget__icon">
                                                <i class="flaticon-chat-1"></i>
                                            </div>
                                            <div class="kt-widget__details">
                                                <span class="kt-widget__title">598 Comments</span>
                                                <a href="#" class="kt-widget__value kt-font-brand">View</a>
                                            </div>
                                        </div>

                                        <div class="kt-widget__item">
                                            <div class="kt-widget__icon">
                                                <i class="flaticon-network"></i>
                                            </div>
                                            <div class="kt-widget__details">
                                                <div class="kt-section__content kt-section__content--solid">
                                                    <div class="kt-media-group">
                                                        <a href="#" class="kt-media kt-media--sm kt-media--circle" data-toggle="kt-tooltip" data-skin="brand" data-placement="top" title="" data-original-title="John Myer">
                                                            <img src="/metronic/themes/metronic/theme/default/demo2/dist/assets/media/users/100_1.jpg" alt="image">
                                                        </a>
                                                        <a href="#" class="kt-media kt-media--sm kt-media--circle" data-toggle="kt-tooltip" data-skin="brand" data-placement="top" title="" data-original-title="Alison Brandy">
                                                            <img src="/metronic/themes/metronic/theme/default/demo2/dist/assets/media/users/100_10.jpg" alt="image">
                                                        </a>
                                                        <a href="#" class="kt-media kt-media--sm kt-media--circle" data-toggle="kt-tooltip" data-skin="brand" data-placement="top" title="" data-original-title="Selina Cranson">
                                                            <img src="/metronic/themes/metronic/theme/default/demo2/dist/assets/media/users/100_11.jpg" alt="image">
                                                        </a>
                                                        <a href="#" class="kt-media kt-media--sm kt-media--circle" data-toggle="kt-tooltip" data-skin="brand" data-placement="top" title="" data-original-title="Micheal York">
                                                            <img src="/metronic/themes/metronic/theme/default/demo2/dist/assets/media/users/100_3.jpg" alt="image">
                                                        </a>
                                                        <a href="#" class="kt-media kt-media--sm kt-media--circle" data-toggle="kt-tooltip" data-skin="brand" data-placement="top" title="" data-original-title="Micheal York">
                                                            <span>+5</span>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <!--end::Portlet-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end:: Content -->

        <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deletemodal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                    {{ csrf_field() }}
                <div class="modal-header">
                    <h5 class="modal-title" id="deletemodallabel">Please Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    All data related to this rules will be deleted and can't be undone!
                    {{-- <input type="hidden" name="id" id="id"> --}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger" id="btndeleteRules" >Delete</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
    "use strict";
// Class definition


    </script>
@endsection